### ISSUE TITLE
マニュアルの修正（再整備） for 1.2.0.beta.3

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1066]
#### いつでも修正できる未修正のもの（チェックがはいったら修正済み）
- [x] #1260 図書館全体のメールアドレスの設定
- [x] 貸出の表示画面に「利用者番号」を表示してほしい #1007　(マニュアルを確認したがこの画面を表示したり言及したりしているページがなかったため修正なし）

#### マニュアル確認まち→ 1.1.2.beta.4 へ送った
- [ ] #1172 モジュール追加方法の修正: enju_bookmark
- [ ] #1171 モジュール追加方法の修正: enju_purchase_request

#### 開発・確認系のissueのクローズ待ち中→ 1.1.2.beta.4 へ送った
- 表記ゆれ検索対応の開発待ち：
  - [ ] #904 検索の異体字対応をEnju標準で対応させる
- 書誌情報の著者名の自動補完系：
  - [ ] #1108 書誌情報の編集時に著者名の自動補完
  - [ ] #935 書誌情報の新規入力時に著者名の自動補完
- その他開発待ち：
  - [ ] #409 要望：TSVインポートでインポート省略した行がある場合の状態は「完了」でなく「完了（注意あり）」としてほしい
  - [ ] #556 添付ファイルの全文検索
  - [ ] #990 貸出の一覧でのTSV書き出しは延滞の日数指定を変えても常に1日以上延滞分だけを出力
- 確認待ち系
  - [ ] #799 パスワードを忘れましたか？を使うと、「検索サーバに不具合があるようです」が出る
  - [ ] #766 OAI-PMH: ListRecordsのresumptionToken対応

#### 質問答えてissueのクローズ待ち中→ 1.1.2.beta.4 へ送った
- 質問答えて待ち：
  - [ ]  #1047 [貸出規則の一覧]　?　これ、何ですか?　後、システム設定のどこかにあったほうがよさそう。 
  - [ ] #715 書影の取得元：Amazonの動作確認、設定方法を文書化
#### 1.1.2.beta.4 へ送ったもの
- [ ]  すぐに修正できる #1040 「貸出期限切れの資料の一覧」のTSVのヘッダを出力してほしい
- [ ] すくに修正できる： #1043 貸出履歴のTSVにヘッダを出力してほしい
- [ ] すぐに修正できる： #984 バグ：貸出履歴のRSSが最初のページ分がつねに表示される→最新500件を表示するように修正
- [ ] すぐに修正できる #998 バグ：予約の一覧のRSSが最初のページ分がつねに表示される→最新500件表示されるように修正 
- [x] 修正必要なし：貸出画面等でのAjax動作（1.2系） #1189
- [x] 修正必要なし：メニューの予約の一覧をクリックするとエラー画面になる #949
- [x] 修正必要なし：LC検索が動作しない問題
#### 1.1.2.xへ送ったもの
- [ ] #1111 統合漢字インデクスのデータをEnjuで利用できるようにする
- [ ] #1111 統合漢字インデクスのデータをEnjuで利用できるようにする
#### 1.1.2マニュアル作業からの継続（残り）：できればやりたいが余裕があったらなもの
- 運用マニュアル
  - [x]  4-9 ★2 [【Column】TSVファイルで出力される項目](https://next-l.github.io/manual/1.2/enju_operation_4.html#bib_tsv_export) の項目の詳細に説明した部分を削除し、Web API マニュアル 1-1-1 を参照するように変える （★1のあとにやる）
- 利用者マニュアル
  - [x] 1-8-3 TSVエクスポート例を移動しリンクをはる(★1のあとにやる) 
  - [x] 書誌詳細のTSVエクスポート例を移動し3-2-1にリンクを張る（★3のあとにやる）
  - [ ] 1-9 購入リクエストを出す（要：モジュールインストール）（所蔵のない書誌のみ表示）
  - [ ] 催し物を確認する
  - [ ] 図書館の情報を閲覧する
- Web APIマニュアル
  - [ ] 第1章 検索結果一覧を取得する
    - [x] ★1 1-1 TSV
    - [ ] 1-2 RDF
    - [ ] 1-3 RSS
  - [ ] 第2章 検索詳細を取得する
    - [x] ★3 2-1 TSV （★2のあとに修正する）
    - [ ] 2-2 RDF
    - [ ] 2-3 RSS
  - [ ] 第3章 OpenSearch 
  - [ ] 第4章 OAI-PMH
  - [ ] 第5章  SRU
- 全体
  - [ ] コラムは緑、メモは水色　に統一する
- その他いろいろ
  - [ ] 請求記号ラベルの表示について
  - [ ] 所蔵情報の新規入力画面の説明に、ひとつひとつの項目について詳細な説明を書く
  - [ ] 書誌詳細の右メニューの説明をひとつひとつ書く
  - [ ] 書誌詳細のひとつひとつの項目について詳細な説明を書く
#### 修正済み（アーカイブ）
- [x] #1053 既にある書誌に、所蔵を追加するTSVインポートをする場合に「item_identifier」がない場合は作成されない
- [x]  #1019 書誌と所蔵のTSVインポートで書誌と「請求記号」だけ指定すると所蔵情報が作られない（エラーもでない）
- [x] #1094 書誌編集画面のタイトル等の入力欄の幅を広く（長く）する
- [x] #1106 雑誌の各号単位の情報に入力されたISBNが表示されない・・・当該ISBNが表示されるようなスクリーンショットや説明がマニュアルになかったので特に修正の必要なし
- [x] #818 提案：NDLサーチインポートの画面に同じキーワードでNDLサービスを探すリンクをつけてはいかが？ 
- [x]  #1058 雑誌の「資料が見つかりませんでした」は「資料がまだ登録されていません」に
- [x] #1062 「図書館全体の設定」は「システム全体の設定」にしませんか?
- [x] #1063 「図書館全体の設定の一覧」はいらないのでは? 
- [x] #938 ログイン画面でのメッセージが多言語に対応していない
- [x] #931 利用者アカウントの表示の右メニューに「貸出資料の新規作成」リンクを追加してほしい 
- [x]  #930 利用者アカウントの表示の右メニューのアンカー名「貸出」「予約」「購入力リクエスト」に「の一覧」を付けてほしい
- [x] #991 ほんとうですか? に代わるメッセージラベル 
- [x] #979 貸出セッションの新規作成の右メニューの[返却]を[返却の新規作成]に変える
- [x] #954 催し物の詳細表示の右メニュー「削除」リンクを追加
- [x] #997 予約の新規作成の次の「予約の表示」画面の右メニュー[戻る]は[予約の一覧]にするべき
- [x] #951 バグ：貸出・予約・返却→貸出履歴の画面で「返却済み」のレコードが表示されない
- [x] #996 [貸出の編集] 画面の右メニューの[戻る]リンクが戻るになっていない
- [x] #995 [貸出の表示] 画面の右メニューの[戻る]リンクが戻るになっていない
- [x] #927 バグ：librarian権限以上のログインユーザの発注リストの購入一覧に自身の登録した購入リクエストしか表示されない
- [x] #1045 所蔵の新規作成の右メニューの「戻る」のリンク先が戻るではない
- [x] #967 librarian権限以上でログインしたときの[アカウント]リンクをたどった先の画面の[予約の一覧]リンク先の画面を変える
- [x] #968 librarian権限以上でログインしたときの[アカウント]リンクをたどった先の画面の[貸出の一覧]リンク先の画面を変える（フェーズ1）
- [x] #983 バグ：貸出履歴のTSVが最初のページ分がつねに表示される→最新500件になるように修正
- [x] #1036 ユーザインポートで利用者番号に不正な文字を含む場合にアカウント情報だけが作られてしまう
- [x] #929 一般ユーザーでログインした時に、利用者情報の編集で（×「図書館」が入力できない）「図書館」「利用者グループ」「参照に必要な権限」が表示されない
- [x] #1087 詳細検索の出版日・受入日・ページ数欄で「~」を使う
- [x] #408 要望：分類のTSVインポートの方式をヘッダで区別するようにしてほしい
- [x] #407 要望：件名のTSVインポートの方式をヘッダで区別するようにしてほしい
- [x] #854 書誌詳細画面の .txt としてTSVエクスポートされるものと、全件TSVエクスポートを揃える
- [x] #1086 件名標目の種類と分類の種類の表示名の大文字／小文字を正確に→初期投入データにLCSH,NDC8を追加する
- [x] #750 言語の「ネイティブ名」ってどこで必要になるのですか？
- [x] #1074 「貸出の表示」画面に、右メニューの「貸出の一覧に戻る」がなくなってしまっている
- [x] #1107 「ISBNインポートのリクエストの新規作成」の入力欄が狭い
- [x] #1004 バグ?：新しい貸出期限日?　貸出期限日を変更する処理をしても変わりません
- [x] #324 バグ：librarian権限以上のログインユーザの購入一覧に自身の登録した購入リクエストしか表示されない
- [x]  #851 雑誌の各号の情報を新規作成する際には親書誌の情報をコピーしてほしい
- [x] #988 フッタをmarkdownで編集できるようにしてほしい（多言語対応ありに）
  - [x] #1144 （当面をしのぐため）画像の置き場は enju/public/assets/以下でよいですか？
  - [x] #1131 (当面の暫定で)ヘッダーに画像を含む文章を書く方法，画像をアップロードする場所などについてマニュアルに記載して欲しい
  - [x] #1118 (当面の暫定で)フッターに画像を含む文章を書く方法，画像をアップロードする場所などについてマニュアルに記載して欲しい
  - [x] #1145 正しいURL教えてください（マニュアルリンク切れURLについて）
- [x] #1071 ISBNハイフン付きでキーワード検索するとヒットしない　→ これは仕様?　それともバグ?
- [x] #1092 検索結果一覧の表の最右の列に常に「所蔵新規作成」（もしくは「所蔵作成」）リンクを付ける
- [x]  #881 ISBN 表示にハイフンを （すでに差し替え済み ref https://next-l.github.io/manual/assets/images/1.1/image_operation_244_2.png )
- [x] #857 検索結果一覧の.txt としてTSVエクスポートされるものと、全件TSVエクスポートを揃える
- [x] #1135 検索結果一覧のソートの「次の項目で並べ替える:」ラベルを消して、右寄せにする（英語対応のため） 
  - [x] ↑ができたらやる #570 要望：出版日(出版年)のソートは降順だけでなく昇順も選択できるようにして欲しい
  - [x] ↑ と一緒に #1134 検索結果一覧の表示件数のメニューがどの表示件数を選んでも必ず「10件ずつ表示」になる
  - [x] ↑と一緒に。 #566 要望：検索された資料一覧の表示件数は10～100件程度で選択できる
- [x]  #1121 書誌情報検索の結果を適合度順ソートしたい
- [x] #1070 資料のエクスポートで編者(contributor)が出力されない（1.2系）
- [x] #1029 要望：書誌のTSVエクスポートで注記を出力するようにしてほしい
- [x] #1028 要望：書誌のTSVエクスポートでアクセスアドレスを出力するようにしてほしい
- [x] #1027 要望：書誌のTSVエクスポートで責任表示を出力するようにしてほしい
- [x] #1096 要望：分類のTSVエクスポートの方式をヘッダで区別するようにしてほしい
- [x] #1026 要望：書誌のTSVエクスポートで分類を出力するようにしてほしい　（★↑と同時に修正可）
- [x] #1095 要望：件名のTSVエクスポートの方式をヘッダで区別するようにしてほしい
- [x] #1147 検索結果一覧や書誌詳細のTSVエクスポートで利用者向けにださないほうがよい項目（Librarian権限以上のときにだけ出す項目）があるかも？（例：書店、予算種別、購入価格など）
#### 修正の必要なし
- [x] 著者情報をもつ書誌情報を編集ができない #1140 
- [x]  #529 依存ライブラリの変更：認可管理：cancancan→pundit
- [x]  #1183 ManifestationsControllerにてRailsエラー：undefined local variable or method `store_location' 
- [x]  #912 依存ライブラリの変更：検索：sunspot 2.2.0 / Solr 4.x→sunspot 2.2.1 / Solr 5.x
- [x]  #1073 TSVエクスポートで「処理待ち」になったまま変わりません
- [x]  #1081 編集画面にすでに登録された識別子が表示されない（識別子が修正できない）
- [x]  #989 1.2系：購入リクエストモジュールが動作しない
- [x]  #1083 「図書館全体の設定」の表示画面がGuestやUser権限で見えてしまう。
- [x]  #1072 Librarian権限以上でログインすると「所蔵の新規作成」が検索結果一覧に必ず表示される
- [x]  #993 バグ：パスワード変更へのリンクがありません　1.2系用
- [x] #884 NDLサーチ検索によるインポートで失敗する (別issueに移行のためこのissueでは修正の必要なし)
- [x] #217 要望：利用者インポートの結果の右メニューのTSVの1行目と2行目を統合してほしい
- [x] #883 書誌詳細ページにてJavaScriptエラー
- [x] #1097 1.2系の新規インストールで、書誌詳細を見ようとするとWe're sorry に
- [x] #1061 1.2系の新規インストールしたEnjuにて書誌一覧表示でRailsエラー（get_subject周り？）（一般用のマニュアルの修正は必要なし。ハッカー用もたぶん修正は必要ないのじゃないかな）
- [x] #964 バグ：ログインしないでカレンダー表示すると「操作を進めるには、図書館員としてログインする必要があります。ログイン」 ・・・利用者マニュアルに現在は、カレンダーを見る機能を説明していないので、どうせ新規作成するのでいまのところは修正の必要なし。
- [x] #1076 開催日と催し物の表示の右メニューに[開館日と催し物の一覧]リンクがない・[戻る]リンクがある（元にもどしただけなので修正の必要なし）
- [x] #950 参照権限Administratorのユーザの詳細情報を閲覧しようとするとアクセス拒否
- [x] #944 1.2系で設定画面が表示できない
- [x] #886 書影があるはずなのに表示されない
- [x] #1105 雑誌の各号単位の書誌情報に入力した説明情報が検索でヒットしない
- [x] #1103 400 Bad Request Request / Header Or Cookie Too Large
- [x] #727 図書館の地図が表示されません
- [x] #1078 [利用者インポートの結果の一覧]リンクが[戻る]になってしまっている
- [x] #1013 バグ：予約の取り置き済みになったときの予約の一覧の表の表示がおかしい 1.2.0用
- [x] #1048 所蔵の詳細表示の右メニューでUser権限でアクセスできないリンク[貸出規則の一覧]と[貸出履歴]が表示される・・・もともと利用者むけマニュアルに所蔵の詳細画面の説明はないので修正は必要ないこととする
- [x] #874 ISBNインポートで版情報の取り込みができない(（とくにそれ専用な画面があるわけじゃないので修正箇所はない）)
- [x] #925 一般ユーザの「購入リクエスト一覧」の表示に発注リストが表示される (利用者むけマニュアルには購入リクエスト機能の説明はないので今回は修正なし)
- [x] #972 書影に border を付ける  スクリーンショットを差し替えるほどでもないので特に修正しない
- [x] #1025 検索結果一覧の「；」が変なときにでてきます。（スクリーンショット差し替えるほどでもないと思うので修正しない） 
- [x] #1072 Librarian権限以上でログインすると「所蔵の新規作成」が検索結果一覧に必ず表示される
- [x] #1076 開催日と催し物の表示の右メニューに[開館日と催し物の一覧]リンクがない・[戻る]リンクがある
- [x] #1046 ある所蔵の表示のメニューの[貸出規則の一覧]をクリックした先が変（マニュアルでは「貸出規則の一覧についてはまだかいていないので修正なしでよいことにする）
- [x] #1143 1.2系のフッターのマニュアルのリンクを1.2のものに変えてほしい （特に修正箇所はないはず）
- [x] #1142 雑誌のタイトルレベルのレコードに「所蔵作成」リンクがでてしまっている（特に修正箇所ないはず）
- [x] #1149 雑誌のタイトルレベルの表示で[削除]リンクが表示されない
- [x] #1156 検索結果詳細のTSVエクスポートでWe're sorry になる 

( #975 )

**Comment by yegusa** [comment]
1.1.2.beta.3 がリリースされたので、クローズします。

**Comment by yegusa** [comment]
#1260 がでてきたので、いったんリオープンします。

**Comment by yegusa** [comment]
メモ：

このissueのマニュアル記入チェックリストを網羅しているかどうかは、確認ずみなので、

-  #1260 図書館全体のメールアドレスの設定
-  貸出の表示画面に「利用者番号」を表示してほしい #1007

この残りの2つさえやれば、このissue はクローズできる。

**Comment by yegusa** [comment]
全て修正したのでクローズする。
