### ISSUE TITLE
マニュアルの修正（再整備） for 1.2.0.beta.4

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1191]
#### いつでも修正できる未修正のもの（チェックがはいったら修正済み）

- [x] #1176 検索結果のRDF/XML形式がレコード単位になっていない
- [x] #935 書誌情報の新規入力時に著者名の自動補完（自動補完機能についてのやり方を追記すること）
- [x] #980 貸出資料の新規作成から利用
  者番号を入れたあとの画面の利用者情報の表示の工夫
- [x] #795 除籍画面を使って、貸出中の資料が、除籍処理できてしまう（借りた状態のまま、除籍処理されてしまう）  -> ひとこと、貸出中のものはエラーがでて除籍できないという旨をマニュアルに追記する予定
- [x] ページ数と大きさ
  - [x] #368 要望：書誌データにdimensionsフィールドの追加
  - [x] #333 要望：書誌データにextentフィールドを追加
  - [x] #1206 書誌詳細の「ページ数と大きさ」について、間に「 ; 」を入れてほしい
  - [x]  #1220 書誌データTSVエクスポートにおいてextent, dimensionsを出力する
  - [x] #1207 NDLサーチ検索書誌インポートで、大きさ(dimensions）を記録するようにしてほしい
  - [x] #1202 NDLサーチ検索書誌インポートで、ページ数（extent）を記録するようにしてほしい
- [x] #1172 モジュール追加方法の修正: enju_bookmark
- [x] #1163 提案：CiNiiBooksインポートの画面に同じキーワードで同サービスを探すリンクをつけてはいかが？
- [x] #1162 提案：米国議会図書館検索インポートの画面に同じキーワードで同サービスを探すリンクをつけてはいかが？
- [x] #1040 「貸出期限切れの資料の一覧」のTSVのヘッダを出力してほしい
- [x] #1043 貸出履歴のTSVにヘッダを出力してほしい
- [x] #984 バグ：貸出履歴のRSSが最初のページ分がつねに表示される→最新500件を表示するように修正
- [x] #998 バグ：予約の一覧のRSSが最初のページ分がつねに表示される→最新500件表示されるように修正 
- [x] #932 利用者の新規作成の右メニューの「インポート」を「利用者のインポート用ファイルの新規作成」に
#### 質問答えてissueのクローズ待ち中・・・1.2.xに送ったので、1.2.0.beta.4では修正の必要なし「
- 質問答えて待ち：
  - [ ]  #1047 [貸出規則の一覧]　?　これ、何ですか?　後、システム設定のどこかにあったほうがよさそう。 
  - [ ] #715 書影の取得元：Amazonの動作確認、設定方法を文書化
#### 開発・確認系のissueのクローズ待ち中 -> 1.2.xへ移動のため　1.2.0.beta.4では修正の必要なし
- 表記ゆれ検索対応の開発待ち：
  - [ ] #904 検索の異体字対応をEnju標準で対応させる
- その他開発待ち：
  - [ ] #409 要望：TSVインポートでインポート省略した行がある場合の状態は「完了」でなく「完了（注意あり）」としてほしい
  - [ ] #556 添付ファイルの全文検索
  - [ ] #990 貸出の一覧でのTSV書き出しは延滞の日数指定を変えても常に1日以上延滞分だけを出力
- 確認待ち系
  - [ ] #766 OAI-PMH: ListRecordsのresumptionToken対応
- その他
  - [ ] #790 所蔵の編集画面：借りられている本を除籍できてしまう（借りた状態のまま、除籍処理されてしまう） 
  - [ ] #713 書影の取得元を複数登録できるようにする
  - [ ] #791 所蔵の編集画面：予約の「取置済み」の本を除籍できてしまう（予約の「取置済み」状態のまま、除籍処理されてしまう）
  - [ ] #794 除籍画面をつかって、予約取置済み資料が、除籍できてしまう（予約の「取置済み」状態のまま、除籍処理されてしまう）
  - [ ] #868 User権限でログインしたときに「予約」リンクがでません。 
  - [ ] #982 貸出履歴の右メニューで予約の[はい] [いいえ]が正常な動作をしない
#### 1.1.2.xへ送ったもの
- [ ] #1111 統合漢字インデクスのデータをEnjuで利用できるようにする
- [ ] #1111 統合漢字インデクスのデータをEnjuで利用できるようにする
#### 1.1.2マニュアル作業からの継続（残り）：できればやりたいが余裕があったらなもの
- 運用マニュアル
  - [x]  4-9 ★2 [【Column】TSVファイルで出力される項目](https://next-l.github.io/manual/1.2/enju_operation_4.html#bib_tsv_export) の項目の詳細に説明した部分を削除し、Web API マニュアル 1-1-1 を参照するように変える （★1のあとにやる）
- 利用者マニュアル
  - [x] 1-8-3 TSVエクスポート例を移動しリンクをはる(★1のあとにやる) 
  - [x] 書誌詳細のTSVエクスポート例を移動し3-2-1にリンクを張る（★3のあとにやる）
  - [ ] 1-9 購入リクエストを出す（要：モジュールインストール）（所蔵のない書誌のみ表示）
  - [ ] 催し物を確認する
  - [ ] 図書館の情報を閲覧する
- Web APIマニュアル
  - [ ] 第1章 検索結果一覧を取得する
    - [x] ★1 1-1 TSV
    - [ ] 1-2 RDF
    - [ ] 1-3 RSS
  - [ ] 第2章 検索詳細を取得する
    - [x] ★3 2-1 TSV （★2のあとに修正する）
    - [ ] 2-2 RDF
    - [ ] 2-3 RSS
  - [ ] 第3章 OpenSearch 
  - [x] 第4章 OAI-PMH（4章じゃないが作成済み）
  - [ ] 第5章  SRU
- 全体
  - [ ] コラムは緑、メモは水色　に統一する
- その他いろいろ
  - [ ] 請求記号ラベルの表示について
  - [ ] 所蔵情報の新規入力画面の説明に、ひとつひとつの項目について詳細な説明を書く
  - [ ] 書誌詳細の右メニューの説明をひとつひとつ書く
  - [ ] 書誌詳細のひとつひとつの項目について詳細な説明を書く
#### 修正済み（アーカイブ）
- [x] #546 バグ？：NDLサーチ検索によるインポートでのタイトル「じゃらん」になる（「じゃらん 関東・東北」）（雑誌のインポート） 修正する場所がないので修正なし
- [x] #799 パスワードを忘れましたか？を使うと、「検索サーバに不具合があるようです」が出る・・・@nabetaがマニュアル修正したようなので一旦クローズする。
- [x]  <s>#1139 librarian権限で貸出規則の一覧の[削除]リンクをクリックすると「アクセスが拒否された」となります</s>・・・そもそも「貸出規則の一覧」についての説明がマニュアルにないので、今回は修正箇所なしとする。
- [x]  <s>#1138 librarian権限で貸出規則の一覧の[編集]リンクをクリックすると「アクセスが拒否された」となります</s>・・・そもそも「貸出規則の一覧」についての説明がマニュアルにないので、今回は修正箇所なしとする。
- [x] #1219 DCNDL出力においてextent, dimensionsを出力する・・・OAI-PMHのDCNDL出力のissueで、こちら、DCNDL出力の具体例はマニュアルにないので、特に修正箇所なし
- [x] #717 書影の取得元：版元ドットコム
- [x] #1171 モジュール追加方法の修正: enju_purchase_request
- [x] #691 OAI-PMH: DC-NDL対応
- [x] #1211 OAI-PMH: DC-NDL対応のマニュアルがない
#### 修正必要なし（アーカイブ）
- [x] #1108 書誌情報の編集時に著者名の自動補完 バグ修正系なのでマニュアル修正なしで良いこととする（新規作成時に著者名の自動補完について書いているのもある）
- [x] #1209 CiNii Books 検索書誌インポートで、大きさ(dimensions）を記録するようにしてほしい
- [x] #1204 CiNii Books 検索書誌インポートで、ページ数（extent）を記録するようにしてほしい
- [x] #1208 米国議会図書館検索書誌インポートで、大きさ(dimensions）を記録するようにしてほしい
- [x] #1203 米国議会図書館検索書誌インポートで、ページ数（extent）を記録するようにしてほしい
- [x] 著作の形態の新規作成へのリンクがありません #92 修正箇所見当たらず
- [x] 図書館の地図が表示されません #727
- [x] LC検索が動作しない問題 #1184
- [x]  #1215 OAI-PMH: ListRecordsリクエストのfrom/until指定が効かない（バグ修正のため）
- [x]  #1217 NDLからのインポート時にエラー（InvalidURI）（バグ修正のため）
- [x]  #1218 ISBNインポート時にuninitialized constant ImportRequest::EnjuNiiエラーが出る（バグ修正のため）
- [x]  #1195 所蔵情報の一覧においてファセット選択と受入日絞り込みを同時に行えない（バグ修正のため）
- [x] #1174 検収機能で「在架」状態にしても所蔵資料検索でのファセットに反映されない
- [x] 貸出画面等でのAjax動作（1.2系） #1189
- [x] メニューの予約の一覧をクリックするとエラー画面になる #949
- [x] LC検索が動作しない問題
- [x] #1190 1.2系でメール送信ができない
- [x] #1034 仮想マシンのnginx設定：client_max_body_size上限をあげたい
- [x] #936 enju_leaf-1.2へのアップデート方法 #936
- [x] #1186 ドキュメント Roadmapを更新する
- [x] #1185 PaperTrail 5での警告
- [x] #1187 1.2.0リリース情報を書く
- [x] #1105 雑誌の各号単位の書誌情報に入力した説明情報が検索でヒットしない
- [x] #1161 リリースプロセスの簡便化
- [x] #1127 1.2開発版を新規インストールをした場合にenju_leaf:setupでエラーになる
- [x]  #1151 1.2.0系の仮想マシンのメモリは2048MBにする
- [x] #769 すでに分類記号が登録されている分類をつけた書誌が作成できない 
- [x] #1030 取り置き済みの所蔵がある書誌に対して、新規の所蔵を作ろうとするとWe're sorryになる
- [x] #1192 ISBN登録時に同名の出版社が複数ある場合にエラーとなる
#### 修正しないことに　（こまかいことなのでしなくていいと判断）
- [x] アイコンの vertical-align を適切に #1150

( #975 )

**Comment by yegusa** [comment]
マニュアル記入の必要性のリストアップは終了したので、「いつでも修正できる未修正のもの（チェックがはいったら修正済み）」の節のみを終了させたら、このissueをクローズできる

**Comment by yegusa** [comment]
一通り修正したのでクローズする。
