### ISSUE TITLE
マニュアルの修正（再整備） for 1.2.1

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1248]
#### 今すぐマニュアル修正可能
- [x] 要望：「条件を詳しく指定して検索」に「件名」の項目が欲しい #575
- [x] 要望：「条件を詳しく指定して検索」に「本棚」（所蔵場所）項目が欲しい #576
- [x] 「システム全体の設定の編集」画面の「色」に[追加]、[削除]リンクがついている→[[追加][削除]はいらない #1098
- [x] TSVエクスポートで、書誌情報にこれまでの貸出回数（累計）を出力して欲しい #1254
- [x] NDC10版対応 #1198
- [x] TSV書誌インポートで、ページ数(extent）を記録するようにしてほしい #1205
- [x] 資料種別(carrier_type)をエクスポート出力する #1251
- [x] 書誌情報にこれまでの貸出回数（累計）を表示して欲しい #877
- [x] openBD 対応 #1249
- [x] 「資料の形態の一覧」画面に、「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像を表示できるようにする #1245
- [x] 「資料の形態の編集」画面で、資料の形態のアイコン画像を登録できるようにする #522 

#### マニュアル修正確認
<s>- [ ] デフォルトのインストールテンプレートで mailers キューを指定していない。 #1242</s> とりあえずいいことにする

#### 修正済み（アーカイブ）

- [x] フッターのバージョン表記の方法を文書化する #1239
- [x] 新規インストール時に、フッターは __VERSION__ を使うようになっているか確認・なっていなければそうなるようにする #1247

#### 1.1.2マニュアル作業からの継続（残り）：できればやりたいが余裕があったらなもの
- 運用マニュアル
  - [ ] 1-9 購入リクエストを出す（要：モジュールインストール）（所蔵のない書誌のみ表示）
  - [ ] 催し物を確認する
  - [ ] 図書館の情報を閲覧する
- Web APIマニュアル
  - [ ] 第1章 検索結果一覧を取得する
    - [ ] 1-2 RDF
    - [ ] 1-3 RSS
  - [ ] 第2章 検索詳細を取得する
    - [ ] 2-2 RDF
    - [ ] 2-3 RSS
  - [ ] 第3章 OpenSearch 
  - [x] 第4章 OAI-PMH（4章じゃないが作成済み）
  - [ ] 第5章  SRU
- 全体
  - [ ] コラムは緑、メモは水色　に統一する
- その他いろいろ
  - [ ] 請求記号ラベルの表示について
  - [ ] 所蔵情報の新規入力画面の説明に、ひとつひとつの項目について詳細な説明を書く
  - [ ] 書誌詳細の右メニューの説明をひとつひとつ書く
  - [ ] 書誌詳細のひとつひとつの項目について詳細な説明を書く

### 修正必要なし
- 書誌の検索結果一覧や詳細表示で登録した資料形態のアイコンを表示できるようにする #1243
- 1.2.1リリース作業 #1255
- ファセット検索後にソート方式を切り替えた場合、絞り込み条件を引き継がない #1270
- 1.2.1リリースノート文 #1275
- 複数のファセットを同時に選択した絞り込み検索が行えない #1196
- 本棚の並びの変更ができない #1197
- foremanのエラーでどの手段でもインストール・起動が行えない #1236
- システム全体の設定が開けない＋図書館の新規作成が出来ない（Heroku＋EC2 Solr版） #1237
- init登録　Ubuntu 16.04 LTS #1241
- LOC検索の修正対応 #1252
- 「資料の形態」の既存アイコンの保存場所を変更する #1256
- ライブラリアンが貸出期間の延長時に誤った日付を入力するとRailsエラー #1257
- rspec実行時にエラー #1259
- 複数の利用者情報が同一ユーザに紐付いてしまう #1261 
- cron_log.logにrake enju_biblio:importのエラーが出力され続ける #1263 
- 既存の資料の形態アイコンが表示できない #1265
- 未ログイン状態で資料の形態アイコンが表示できない #1266
- 貸出の一覧画面にて絞り込み検索が動作しない #1269 
- 1.2.0->1.2.1更新の際にrake enju_leaf:upgrade実行時にエラー #1274
- 公式サイトの1.2.0のVirtualBoxでbundle updateしたら起動できなくなった(production環境) #1271

( #975 )

**Comment by yegusa** [comment]
1.2.1 リリース後にひととおりマニュアルに記入すべきかどうかのリストアップは終了。
マニュアルを記入すべきことがらを書いたらクローズできるはず。

**Comment by yegusa** [comment]
クローズします。余裕があったらな奴は、1.2.2へ移動。
