### ISSUE TITLE
マニュアルの修正（再整備） for 1.2.2

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1279]
##### その他

- [x] Enjuくんのバナーをフッターかヘッダーに設定する #1294
- [x] 初期設定として、NDC10版のラベルを設定すること #1276
- [x] 「資料の形態の表示」（詳細）画面に、「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像を表示できるようにする #1244 
- [x] マニュアルサイトからPDF版へのリンクを追加する #1280
- [x] TSV書誌インポートで、大きさ(dimensions）を記録するようにしてほしい #1210

##### TSVエクスポート関係

- [x] 書誌と所蔵のTSVエクスポートの注記や説明の改行をエスケープする #1296 
- [x] 「タイトルのヨミ」をTSV一括エクスポートできるようにしてほしい #1305 
- [x] 「版」を書誌TSVエクスポートできるようにしてほしい #1303 
- [x] Web-API(TSV)に巻号を追加してほしい #1313

##### TSVインポート関係

- [x] TSVインポート時に改行エスケープを戻す処理を加える #1341 
- [x] 「タイトルのヨミ」をTSV一括インポートできるようにしてほしい #1306 (すでにできるかのように、マニュアルには書いてありました)
- [x] 「版」を書誌TSV一括インポートできるようにしてほしい #1302 (すでにマニュアルには記載済みでした)

#### 前マニュアル作業からの継続（残り）：できればやりたいが余裕があったらなもの
- 運用マニュアル
  - [x] 書誌詳細の右メニューの説明をひとつひとつ書く まとまっては書かれていないが分散して書かれているのでよいことに。

#### 修正しないもの(必要ないもの)

- enju_gridにソート切替機能を追加する #1298 
- paperclip 4.3.7 以降でUninitialized Constant Paperclip::Storage::S3::Awsエラーとなる #1289
- enju_gridモジュールが1.2系で未リリース #1291 
- 公式サイトのダウンロードから1.2.2の仮想マシンをダウンロードできるようにする #1347
- デモサーバーにEnjuくんファビコンを設定する #1346
- デモサーバーのヘッダーにEnjuくんロゴをいれる #1345
- Enjuくんのファビコンを設定する #1293
- ISBNの検索がハイフン厳密になっている #1311
- 10桁・13桁を考慮したISBN検索 #1312
- Web-API(TSV)における項目数の不足 #1314
- EC2でのインストール手順だとgemにforemanがない #1336
- マニュアルの記述が古くインストールが行えない #1216
- フッターのMarkdownが解釈されない #1338
- CiNii BooksのSSL化に伴う改変 #1337 
- bundle update できません #1335
- 貸出状態の返却期限に初回の貸出期限が表示される #1307 （バグ修正のため）
- 例によってインストールがマニュアル通りでは行えない #1301 
- パスワード変更が機能しない #1297
- enju_gridモジュールでファセット検索絞り込みが効かない #1292 
- 新規インストール時に bundle exec foreman startにて foreman 実行ができない #1290 
- バグ：利用者アカウントの表示の右メニュー：「戻る」→「利用者の一覧」となっているべき #1278 （バグのため）
- 「Reset password tokenは不正な値です。」と表示されてパスワードをリセットできない #1262
- マニュアルが古くインストールが行えない（Amazon EC2へのインストール） #1234
- メッセージ一覧へのアクセスにてエラー #1233
- rake buildにおいてテスト用データがパッケージに含まれてしまう #1222 
- 任意の識別子登録 #1157 (すでに修正済み)
- バグ：認証付きプロキシへの対応 #402
- Solr で漢字の異体字セレクターを無視する #1101 (すでに修正済み）

(#975)

**Comment by yegusa** [comment]
マニュアルをひととおり書いたので、クローズします。
