### ISSUE TITLE
マニュアルの修正（再整備） for 1.3.0 <s>1.2.3</s>

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1348]
#### すぐに修正できるもの

- [x] コマンド：現在の貸出データ（今までの累計ではなく、今現在の貸し出し状況）を抽出したい #1367
- [x] コマンド：現在の貸出データ（今までの累計ではなく、今現在の貸し出し状況）を抽出したい part 2 #1393
- [x] 「貸出の一覧」のTSV出力に「返却済み」かわかる列を入れて欲しい（画面では表示されている） #1377
- [x] マニュアル：TSVファイルの拡張子は、tsvでもtxtでもよいことを書く #1362
- [x] 一つの書誌に複数のISBNがあるものをTSV書誌一括インポートしたい #1394
- [x] isbnを複数入れた図書の詳細のtsvの場合、一つしか出力されない #1392
- [x] エクスポートの項目に「利用制限」(use_restriction)を追加 #1366 guestで表示されると注付き 
- [x] 国立国会図書館書誌IDを使って書誌の一括インポート機能の追加（ISBNのように） #1389

#### 使い方がわかればマニュアルにかけるもの
- [x] <s> 書誌のTSVインポートでserial 項目（逐次刊行物フラグ？）の使い方を教えてください #1410
</s> 機能がないことがわかったので、1.3.1へ

#### 1.3.0でやっぱりダメだったのでまだ修正していないもの

- [x] <s> エクスポートの項目に「利用制限」(use_restriction)を追加(Librarian,Administratorのみ) #1366 Librarian,Administratorのみで表示されるようになったら、注を消す </s>

#### 修正しないもの(必要ないもの)

- 貸出の時に貸出する資料が表示されない #1409
- 書誌TSVインポートのサンプルからseries_statement_identifierを削除する #1178
- 公式サイトからダウンロードした1.3.0 64bit 仮想マシンの初期設定がおかしい（「図書館」の設定の住所にIbaraki, Tsukubaが入っている） #1400
- 公式サイトからダウンロードした1.3.0 64bit 仮想マシンにsshでログインできない #1401
- デモサーバーで「貸出の一覧」のTSV出力がエラー #1404
- NDL書誌情報取り込みにてbad URIエラーとなる場合アリ #1356
- カレンダーに直近で登録されたイベント10件しか表示されない #1272 
- 標準インストール時に言語設定がされない #1384
- マニュアルの記述が古くインストールが行えない #1216
- Enjuくんの紹介ページ・ダウンロードページをつくる #1295 
- 所蔵の「注記」の表示方法 #1342 （当該スクリーンショットがないため修正の必要なし）
- [Heroku] Enju 1.2.2 への更新手順 (db:migrate) #1352 
- [Heroku] charlock_holmesのビルド時にエラーとなりインストールできない #1376
- 公式サイトのHTTPS化 #1373 
- enju_leaf:quick_install でDBエラーが出る #1372
-  Solr起動エラー #1368 
- ロゴが登録されている場合は上書きしないようにする #1365
- ウェブサイトに新ロゴを置く #1364
- Java9 + Sunspot組み込みSolrの場合、エラーで起動できない #1357
- タイトル表示部分のスペースを広げる #1355
- [Heroku] 1.2.2への更新手順 (routes.rb) #1351
- paperclipセキュリティ対応 #1350
- 開発版のGemfileテンプレートに日本語文字が含まれている #1344
- Next-Lで配布している仮想マシンで、1.2.3開発版をソースから新規インストールできません #1343
- 検索エンジンの設定の異体字の設定で、異体字を再追加した場合にやることを追加 #1159

#### 前マニュアル作業からの継続（残り）：できればやりたいが余裕があったらなもの
- 初期設定マニュアル
  - [ ] grid モジュールのインストール方法を追加する
- 利用者マニュアル
  - [ ] 催し物を確認する（すでに書かれているので）
  - [ ] 図書館の情報を閲覧する
- Web APIマニュアル
  - [ ] 第1章 検索結果一覧を取得する
    - [ ] 1-3 MODS
    - [ ] 1-4 RSS
  - [ ] 第2章 検索詳細を取得する
    - [ ] 2-3 MODS
  - [ ] 第4章 OpenSearch 
  - [ ] 第5章  SRU
- 運用マニュアル
  - [ ] grid モジュールの使い方を書く
  - [ ] 4-2-7 手動で資料を登録する 2. の冒頭（書誌詳細のひとつひとつの項目について詳細な説明を書く）
  - [ ] 書誌に本文URLを登録したときの挙動を書く（動画や静止画を張ったときはどうなるかなど）
- 全体
- その他いろいろ
  - [ ] 請求記号ラベルの表示について
  - [ ] 所蔵情報の新規入力画面の説明に、ひとつひとつの項目について詳細な説明を書く

(#975)
