### ISSUE TITLE
マニュアルの修正（全体インデックス） for 1.3.2

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1445]
マニュアル整備のためのまとめi
- [x] 1.3.2 のissueについて一通り，マニュアル修正がいるかどうか確認
- [x] 必要ならマニュアル修正する
- [x] PDF版を作成
- [x] PDF版を公式サイトへuploadする 
- [x] 公式サイトのwikiページを修正する 

#### すぐに修正できるもの
- [x] 貸出履歴のTSVでuser_numberを出力してほしい #1406
- [x] 資料検索の結果表示項目のカスタマイズについて ( #1435 ) → #1504 で修正 @masao
- [x] NDLサーチのWebAPIの呼び出しにHTTPSを使用する #1438
- [x] 1.3.1 で貸出履歴の貸出ずみの行の削除リンクをクリックしたらWe're sorryになった #1444

#### 修正後・使い方がわかればマニュアルにかけるもの
- [ ] 書誌のTSVインポートでserial 項目（逐次刊行物フラグ？）の実装・使い方を教えてください #1410

#### 修正しないもの(必要ないもの)
- デモサーバー：利用者情報のエクスポートが「失敗」になります #1447
- sqlite3の更新手順 #1441
- sqlite3モジュールエラーで起動できない #1440
- markdown のマニュアルを修正する必要なし #1445
- 出版日付情報のNDL取り込みの精緻化 #1429
- 不具合：除籍済み資料がログインしていない状態で表示されてしまいます #1428
- Rails 5.2対応 #1426
- 利用者グループ画面における貸出区分との関係追加が機能していない #1424
- パスワード変更画面のラベルが英語になっている #1422 (重複のためこちらは無視)
- パスワード変更画面で英語のラベルが混在している #1416
- foreman起動時のポート変更? #1415
- [Heroku] Enju 1.2.2 への更新手順 (db:migrate) #1352
- マニュアルの記述が古くインストールが行えない #1216
- SyntaxError in BasketsController#new #1164
- パスワード変更フォームの変更 #625
- 要望　ファビコンを設定してほしい #391

### 修正済み
- [x] 1.3 系マニュアルのサイト内検索を1.2から1.3に #1408
- [x] iPadで書影を簡単に追加できる #1439
- [x] 資料の表示で「タイトルのヨミ」を表示してほしい #1442

#### 前マニュアル作業からの継続（残り）：できればやりたいが余裕があったらなもの
- 初期設定マニュアル
  - [ ] grid モジュールのインストール方法を追加する
- 利用者マニュアル
  - [ ] 催し物を確認する（すでに書かれているので）
  - [ ] 図書館の情報を閲覧する
- Web APIマニュアル
  - [ ] 第1章 検索結果一覧を取得する
    - [ ] 1-3 MODS
    - [ ] 1-4 RSS
  - [ ] 第2章 検索詳細を取得する
    - [ ] 2-3 MODS
  - [ ] 第4章 OpenSearch 
  - [ ] 第5章  SRU
- 運用マニュアル
  - [ ] grid モジュールの使い方を書く
  - [ ] 4-2-7 手動で資料を登録する 2. の冒頭（書誌詳細のひとつひとつの項目について詳細な説明を書く）
  - [ ] 書誌に本文URLを登録したときの挙動を書く（動画や静止画を張ったときはどうなるかなど）
- 全体
- その他いろいろ
  - [ ] 請求記号ラベルの表示について
  - [ ] 所蔵情報の新規入力画面の説明に、ひとつひとつの項目について詳細な説明を書く

(#975)

**Comment by yegusa** [comment]
やったよー

**Comment by masao** [comment]
了解
