### ISSUE TITLE
マニュアルの修正（全体インデックス） for 1.3.3

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1489]
マニュアル整備のためのまとめ

- [x] 1.3.3 のissueについて一通り，マニュアル修正がいるかどうか確認
- [x] 必要ならマニュアル修正する
- [x] PDF版を作成
- [x] PDF版を公式サイトへuploadする  
- [x] 公式サイトのwikiを修正する

### マニュアル修正する
- [x] リリース前のパッケージを使用している場合に「システムの基本的な情報の表示」でコミットのハッシュを表示 #1480
- [x] 新規予約にアクセスすると「アクセス拒否」になる #1458 
- [x] 貸出の編集画面に「利用者番号」を表示してほしい #1008 
- [x] 「所蔵情報の表示」で「貸出規則」というなにも表示されない項目がある #862

### マニュアル修正の必要なし
- OpenBD利用時に書影が枠からはみ出る #1481
- 貸し出し画面で存在しない利用者番号を入力すると警告メッセージにtranslation missingがでる #1475
- 書誌に画像追加するときのボタンを[ファイルを選択]ではなくて[画像を選択]に変えてはどうか？ #1446
- 予約一覧画面にて絞り込み検索が動作しない #1268
- イベント一覧画面で絞り込み検索が動作しない #1267
- ArgumentError in Events#show #1165
- 貸出の一覧でのTSV書き出しは延滞の日数指定を変えても常に1日以上延滞分だけを出力 #990
- OAI-PMH: ListIdentifiersにてmetadataPrefix属性を出力する #762
- ブラウザの検索バーにEnjuを登録したときにアイコンを載せてほしい #390

### 1.3.4のため今回は修正なし（間違えて、1.3.3になってた）。
- <s>Web-API(JSON)に出版者を追加してほしい #1310 </s> 1.3.4だったため
- <s>Web-API(JSON)にISBNが含まれないケースがある #1309 </s> 1.3.4だったため

(#975)

**Comment by yegusa** [comment]
やりました〜

**Comment by yegusa** [comment]
ま、クローズしていいよね。クローズします。
