### ISSUE TITLE
予約有効期限が指定されなかった場合に「予約の期限切れまでの期間」で上書きされないようにする

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#674]
有効期限を指定しなかった場合、期限が勝手に設定されてしまうので、これを無効化すること。
http://enju.next-l.jp/user_group_has_checkout_types/1
（おそらく、この機能自体が不要）
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9020923/f14b6d6e-3863-11e5-8ac1-495b6303f3fa.png)

##ToDo

* [x] a) 開発：有効期限を指定しなかったばあい、期限は設定しないままにする http://dev.next-l.jp/reserves/new?manifestation_id=24403
* [x] b) ↑の確認
* [x] c) ↑のマニュアル修正
* [x] d) 開発：「利用者グループと貸出区分の関係の編集」：利用者グループごとの「予約の期限切れまでの期間」入力をできないようにする http://dev.next-l.jp/user_group_has_checkout_types/1/edit
* [x] e) ↑の確認
* [x] f) ↑のマニュアル修正
* [x] g) 開発：「利用者グループの編集」：利用者グループごとの「予約の期限切れまでの期間」入力をできないようにする http://dev.next-l.jp/user_groups/1/edit
* [x] h) ↑の確認
* [x] i) ↑のマニュアル修正

**Comment by nabeta** [comment]
利用者グループごとの「予約の期限切れまでの期間」をフォームから削除しました。
http://dev.next-l.jp/user_group_has_checkout_types/1/edit

また、予約の有効期限の入力欄も削除しています。
http://dev.next-l.jp/reserves/new?manifestation_id=1

**Comment by masao** [comment]
この修正、さすがに後方互換を消すのでまずいと思います。

**Comment by masao** [comment]
予約の有効期限自体は必要ですので、機能自体を削除するのはやめましょう。上書きしないことを実装する必要があると思うのですが。。。

**Comment by masao** [comment]
修正を戻していただけませんか。

**Comment by nabeta** [comment]
フォームを元に戻し、有効期限の自動設定のみを無効にしました。
現時点では「予約の期限切れまでの期間」はなんの効力もありません。

**Comment by yegusa** [comment]
このissueは、

> 有効期限を指定しなかった場合、期限が勝手に設定されてしまうので、これを無効化すること。

この意は、
「有効期限を指定しなかった」ときに、「期限を勝手に設定してしまう」という機能がまずいので、
「有効期限を指定しなかった」ときは、「期限は無限と設定する」という機能に変える
ということです。

> 現時点では「予約の期限切れまでの期間」はなんの効力もありません。

なんで、その機能削除しちゃったんですか？
それは、それでいるのでは？

予約の「有効期限」を設定したときには、設定した「有効期限」を過ぎたら、
予約したことそのものをキャンセルする機能
自体はあってもよい機能だっとおもいますが。

@masao さんの

> （おそらく、この機能自体が不要）

は、いままであった、「予約の期限切れまでの期間」を使えなくしろという意味ではないですよ。
あくまでも、設定していないときにかってに設定しておいた期限（標準では7日間）に
「上書き」されるのがまずいという話。

**Comment by yegusa** [comment]
有効期限を設定しなかったばあい、有効期限には何も設定されないことを確認しました。

設定しなかった場合：
![image](https://cloud.githubusercontent.com/assets/1328499/10090626/9d8de790-636c-11e5-9074-b90daf811857.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10090632/b1f3dcf8-636c-11e5-89f3-4d6e7af84a3f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10090644/d379baaa-636c-11e5-97e6-3ae1d85b72d3.png)


一応：設定した場合
![image](https://cloud.githubusercontent.com/assets/1328499/10090687/3ba96742-636d-11e5-88d4-05e1808d66dc.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10090694/4e52af0c-636d-11e5-92da-3e16a33c4e0f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10090706/6da856a4-636d-11e5-989c-b53192d531a3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by yegusa** [comment]
仮想マシンで、 d), f) の確認作業をしました。
（つまり、「予約の期限切れまでの期間」の利用者グループ全体での設定機能はなくすということですね）
よって、ToDo の e), g) にチェックをいれました。

d) の確認：
![image](https://cloud.githubusercontent.com/assets/1328499/10091169/997067fe-6372-11e5-9e89-b69c7bad5d4c.png)

参考：以前の画面
![image](https://cloud.githubusercontent.com/assets/1328499/10091158/6c0b49aa-6372-11e5-9186-ae65c79af3d5.png)

f) の確認
![image](https://cloud.githubusercontent.com/assets/1328499/10091230/76cae674-6373-11e5-94b5-f160c50fc6ec.png)


参考：以前の画面
![image](https://cloud.githubusercontent.com/assets/1328499/10091210/3671b01c-6373-11e5-856b-cd8cd0b768c0.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by yegusa** [comment]
* マニュアル「3-6 利用者グループと貸出区分の関係を設定する」 の文章とスクリーンショットを修正
よって Todo f) をチェックする。 https://github.com/next-l/manual/commit/9c6bb0bd1b9d47e798e909f5ef236c8210d03101
* マニュアル 「3-4 利用者グループを設定する」には、新規作成のみで、編集の説明がなかったため、
とりあえず、修正箇所がないことを確認。よって、 Todo i) をチェックする。

**Comment by nabeta** [comment]
> なんで、その機能削除しちゃったんですか？
> それは、それでいるのでは？

現状では利用者グループごとの予約期限を削除し、予約情報での予約期限は残っていると思うのですが、それで問題ないでしょうか？

**Comment by yegusa** [comment]
> 現状では利用者グループごとの予約期限を削除し、予約情報での予約期限は残っていると思うのですが、それで問題ないでしょうか？

ええ、とりあえず、それで問題ないということにしたいとおもいます。
あと残り作業はマニュアル書きだけですので、
このissueでは「開発」は、残ってないです。

**Comment by yegusa** [comment]
マニュアルも書いたので、いったんクローズします。
