### ISSUE TITLE
TSV書誌インポート項目チェック 1.1.0リリースに向けて

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#873]
マニュアルづくりのために、動作確認します。
終わったらチェックを入れます。

### 削除
* [x] manifestation_id   できないことを確認　　#805 
* [x] manifestation_identifier　　できないことを確認 #806

### 新規
* [x] manifestation_id できないことを確認 #872
* [ ] manifestation_identifier
* [ ] original_title
* [ ] title_transcription
* [ ] title_alternative
* [ ] title_alternative_transcription
* [ ] statement_of_responsibility
* [ ] periodical
* [ ] edition_string
* [ ] edition
* [ ] volume_number_string
* [ ] volume_number
* [ ] issue_number_string
* [ ] issue_number
* [ ] serial_number
* [ ] series_original_title
* [ ] series_title_transcription
* [ ] series_volume_number_string
* [ ] series_creator_string
* [ ] creator
* [ ] creator_transcription
* [ ] contributor
* [ ] contributor_transcription
* [ ] publisher
* [ ] publisher_transcription
* [ ] publication_place
* [ ] pub_date
* [ ] content_type
* [ ] carrier_type
* [ ] frequency
* [ ] language
* [ ] isbn
* [ ] issn
* [ ] jpno
* [ ] lccn
* [ ] doi
* [ ] ncid
* [ ] subject
* [ ] classification
* [ ] start_page
* [ ] end_page
* [ ] extent_of_text
* [ ] height
* [ ] width
* [ ] depth
* [ ] manifestation_price
* [ ] access_address
* [ ] fulltext_content
* [ ] required_role_name
* [ ] description
* [ ] note
* [ ] dummy
* [ ] series_statement_identifier

### 更新
* [ ] manifestation_id
* [ ] manifestation_identifier
* [ ] original_title
* [ ] title_transcription
* [ ] title_alternative
* [ ] title_alternative_transcription
* [ ] statement_of_responsibility
* [ ] periodical
* [ ] edition_string
* [ ] edition
* [ ] volume_number_string
* [ ] volume_number
* [ ] issue_number_string
* [ ] issue_number
* [ ] serial_number
* [ ] series_original_title
* [ ] series_title_transcription
* [ ] series_volume_number_string
* [ ] series_creator_string
* [ ] creator
* [ ] creator_transcription
* [ ] contributor
* [ ] contributor_transcription
* [ ] publisher
* [ ] publisher_transcription
* [ ] publication_place
* [ ] pub_date
* [ ] content_type
* [ ] carrier_type
* [ ] frequency
* [ ] language
* [ ] isbn
* [ ] issn
* [ ] jpno
* [ ] lccn
* [ ] doi
* [ ] ncid
* [ ] subject
* [ ] classification
* [ ] start_page
* [ ] end_page
* [ ] extent_of_text
* [ ] height
* [ ] width
* [ ] depth
* [ ] manifestation_price
* [ ] access_address
* [ ] fulltext_content
* [ ] required_role_name
* [ ] description
* [ ] note
* [ ] dummy
* [ ] series_statement_identifier

**Comment by yegusa** [comment]
テストを書くことでOKとすることにして、いったんクローズにします。　by WSの議論より。

**Comment by yegusa** [comment]
#889 のほうでやるってことでいったんクローズします。
