### ISSUE TITLE
マニュアルの修正（再整備） for 1.1.2

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#891]
1.1.0リリースに向けて、行っていたマニュアルの再度閲読、修正・追記 #725 の続きです。
全部できなかったので積み残し分を次のリリースに向けてやります。

そこで以下にチェックリストを用意しますので、各自担当箇所を割り当てたりしながら、一通り見直してみるとよいかと思います。
＃修正・追記箇所があれば、直接に修正するなり、Issue登録するなりしてください。

http://next-l.github.io/manual/

* インストールマニュアル
 - [x] 1.1.0時点で、すべて終了!
* 初期設定マニュアル
 - [x] 1.1.0時点で、すべて終了! 
* 運用マニュアル
 - [x] 第1章 Enju概要（1.1.0時点で済 ）
 - [x] 第2章 Enjuを利用する（1.1.0時点で済 ）
 - [x] 第3章 利用者情報を管理する（全体）
 - [x] 3 冒頭
 - [x] 3-1 利用者情報を新規作成する
 - [x] 3-2 既存のデータから利用者情報をインポートする
 - [x] 3-2-1 TSVファイルの作成
 - [x] 3-2-2 TSVファイルのインポート　※ただし、TSVファイル各項目チェックはしてない
 - [x] 3-2-3 失敗した場合について
 - [x] 3-3 利用者のアカウント情報を変更する
 - [x] 3-4 利用者情報を削除する
 - [x] 3-5 利用者情報を表示する
 - [x] 3-6 利用者を検索する
 - [x] 3-7 利用者情報を別システムで管理する
 - [x] 3-8 利用者のエクスポートをする
 - [x] 第4章 図書の受入をする　（4章冒頭の部分の修正も忘れずに）
 - [x] 4-1 図書を発注する
 - [x] 4-1-1 発注リストを作成する
 - [x] 4-1-2 発注したい図書（購入リクエスト）を発注リストに登録する
 - [x] 4-1-3 発注リストを印刷する
 - [x] 4-2 図書を登録する
 - [x] 4-2-1 TSVファイルを読み込んで登録する（1.1.0時点で済 ）
 - [x] 4-2-2 ISBNファイルを読み込んで登録する（1.1.0時点で済 ）
 - [x] 4-2-3 ISBNコードを入力して1件ずつ登録する（1.1.0時点で済 ）
 - [x] 4-2-4 NDLサーチを検索して1件ずつ登録する（1.1.0時点で済 ）
 - [x] 4-2-5 米国議会図書館を検索して1件ずつ登録する（1.1.0時点で済 ）
 - [x] 4-2-6 CiNii Booksを検索して1件ずつ登録する（1.1.0時点で済 ）
 - [x] 4-2-7 手動で資料を登録する（1.1.0時点で済 ）
 - [x] 4-2-8 図書の書誌を編集（修正）する（1.1.0時点で済 ）
 - [x] 4-2-9 TSVファイルを読み込んで更新する
 - [x] 4-2-10 TSVファイルの作り方（図書（書誌））　　※ただし、TSVファイル各項目チェックはしてない
 - [x] 4-3 所蔵情報を登録・一覧表示する
 - [x] 4-3-1 所蔵情報を新規登録する
 - [x] 4-3-2 すでに登録された所蔵情報を修正登録する （キーワードでなく、バーコードで検索とすること）
 - [x] 4-3-3 所蔵情報を一覧表示する
 - [x] 4-3-4 TSVファイルを読み込んで登録する
 - [x] 4-3-5 TSVファイルを読み込んで更新する
 - [x] 4-3-6 TSVファイルを読み込んで所蔵情報を他の書誌につけかえる
 - [x] 4-3-7 TSVファイルを読み込んで削除する
 - [x] 4-3-8 TSVファイルの作り方（所蔵情報）
 - [x] 4-4 図書を検収する　 #867 #868 待ち →とりあえず予約リンクがでないバグがあると書いた
 - [x] 4-5 図書を除籍する（1.1.0時点で済 ）
 - [x] 4-6new 図書を製本する （追記したら、以降の節番号をずらす）
 - [x] 4-<s>6</s>7 新着資料の一覧を表示する（1.1.0時点で済 ）
 - [x] 4-<s>7</s>8 画像を登録する（1.1.0時点で済 ）
 - [x] 4-<s>7</s>8-1 画像の登録（1.1.0時点で済 ）
 - [x] 4-<s>7</s>8-2 画像の一覧表示（1.1.0時点で済 ）
 - [x] 4-<s>8</s>9 書誌と所蔵のエクスポートをする（1.1.0時点で済 ）
 - [x] 4-<s>9</s>10 人物・団体情報を登録する（1.1.0時点で済 ）
 - [x] 4-<s>9</s>10-1 設定項目（1.1.0時点で済 ）
 - [x] 4-<s>9</s>10-2 設定方法（1.1.0時点で済 ）
 - [x] 第5章 雑誌の受入をする
 - [x] 5-0 雑誌登録の基本的な仕組み
 - [x] 5-1 雑誌（シリーズ）を登録する
 - [x] 5-1-1 NDLサーチを検索して登録する
 - [x] 5-1-2 手動で資料を登録する
 - [x] 5-2 個々の雑誌を登録する
 - [x] 5-3 TSVファイルを読み込んで登録する
 - [x] 第6章 貸出・返却・予約を処理する
 - [x] 6-1 貸出をする
 - [x] 6-1-1 資料を貸し出す
 - [x] 6-1-2 利用者カードを忘れた利用者に資料を貸し出す
 - [x] 6-1-3 貸出中の資料の一覧を表示する
 - [x] 6-1-4 貸出の延長手続きをする
 - [x] 6-2 返却を受け付ける
 - [x] 6-3 予約を受け付ける
 - [x] 6-3-1 予約を新規作成する
 - [x] 6-3-2 予約の一覧を表示・印刷する
 - [x] 6-3-3 予約資料を取置済みにする
 - [x] 6-3-4 取置済みの資料を表示する
 - [x] 6-3-5 利用者に予約資料の到着を連絡する
 - [x] 6-3-6 予約の変更・取消をする
 - [x] 6-4 督促の連絡をする
 - [x] 6-5 相互貸借をする
 - [x] 第7章 休館日と催し物を登録する  <s> #958 の件を追記する（詳細表示に削除リンクが1.1.2から追加） </s>
 - [x] 7-1 休館日を登録する
 - [x] 7-2 催し物を登録する 
 - [x] 7-2-1 手動で催し物を登録する
 - [x] 7-2-2 催し物のデータをインポートする　※ただし、TSVファイル各項目チェックはしてない
 - [x] 7-3 カレンダーを利用する
 - [x] <s>第8章 レファレンスを処理する</s>
 - [x] 第<s>9</s>8章 資料を検索する
 - [x] 第<s>10</s>9章 蔵書点検機能を利用する
 - [x] 第<s>11</s>10章 統計機能を利用する
 - [x] 10-1 貸出の統計を取る
 - [x] 10-1-1 利用者別貸出統計を取る　<s> #955　1.1.0, 1.1.1では動かない旨書く</s>
 - [x] 10-1-2 資料別貸出統計を取る
 - [x] 10-2 予約の統計を取る 
 - [x] 10-2-1 利用者別予約統計を取る <s> #956　1.1.0, 1.1.1では動かない旨書く </s>
 - [x] 10-2-2 資料別予約統計を取る <s> #957 　1.1.0, 1.1.1では動かない旨書く </s>
 - [x] 第<s>12</s>11章 印刷その他の機能を利用する（1.1.0時点で済 ）
* 利用者マニュアル
 - [x] 1.1.0時点で、全て終了!（1.1.0時点で済 ）
 - [x] 第1章 資料を検索する（1.1.0時点で済ではなかった（見落とし））  
 - [x] 1-1 キーワードで検索する
 - [x] 1-2 条件を詳しく指定して検索する
 - [x] 1-3 フィールド名や演算子を使って検索する
 - [x] 1-4 検索結果を絞り込む
 - [x] 1-5(new)検索結果一覧を書き出す（検索フィード）
 - [x] 1-6(new)検索結果一覧を書き出す（XML/RDF, MODS, TSV）
 - [x] 1-7(new) 検索結果詳細を書きだす（XML/RDF, MODS, TSV）
 - [x] 1-8(new) 書誌情報を電子メールで送信する（メールアドレス登録していると）
 - [ ] 1-9 購入リクエストを出す（要：モジュールインストール）（所蔵のない書誌のみ表示）
 - [ ] 催し物を確認する
 - [ ] 図書館の情報を閲覧する
* Web APIマニュアル
 - [ ] 第1章 検索結果一覧を取得する
 - [ ] 1-1 TSV
 - [ ] 1-2 RDF
 - [ ] 1-3 RSS
 - [ ] 第2章 検索詳細を取得する
 - [ ] 2-1 TSV
 - [ ] 2-2 RDF
 - [ ] 2-3 RSS
 - [ ] 第3章 OpenSearch 
 - [ ] 第4章 OAI-PMH
 - [ ] 第5章  SRU
* 全体
 - [ ] コラムは緑、メモは水色　に統一する

* バグ修正対応など 1.1.2
 - [x] #959 利用者アカウントの表示の右メニューのアンカー名「貸出」「予約」「購入力リクエスト」に「の一覧」を付けてほしい
 - [x] #960 バグ：librarian権限以上のログインユーザの発注リストの購入一覧に自身の登録した購入リクエストしか表示されない
 - [x] #961 バグ：librarian権限以上のログインユーザの購入一覧に自身の登録した購入リクエストしか表示されない
 - [x] #962 バグ：貸出・予約・返却→貸出履歴の画面で「返却済み」のレコードが表示されない
 - [x] #963 図書館の地図が表示されません（※まだ確認は済んでいないが先行してマニュアルだけは修正済み）
 - [x] #965 librarian権限以上でログインしたときの[アカウント]リンクをたどった先の画面の[貸出の一覧]リンク先の画面を変える 1.1.2用
 - [x] #966 librarian権限以上でログインしたときの[アカウント]リンクをたどった先の画面の[予約の一覧]リンク先の画面を変える 1.1.2用
 - [x] 一般ユーザーでログインした時に、利用者情報の編集で「図書館」「利用者グループ」「参照に必要な情報」が表示されない 1.1.2用 #970 
 - [x] バグ：パスワード変更へのリンクがありません #971　（※まだこのバグが修正されていないが先行してブラウザの開発機能をつかってパスワード変更のリンクを追加することでマニュアルの修正済み）
 - [x] 　#1016　バグ：一般ユーザーの場合（?）予約の取り置きのお知らせが来ません 
 - [x] #1009 #1005 [貸出期間延長] の時の「更新回数」はどういう動きを想定しているか教えてほしい

* どこに書けばよいかわからないのでとりあえず
 - [x]  #987 フッタの内容の変更方法を教えてほしい（マニュアルに書きたい） 
 - [x] #1024 「条件を詳しく指定して検索」の画面の修正方法をおしえてください #1024
 - [x] #1021 仮想マシンWebサーバーの設定方法（書誌のTSVインポートで大きなファイルの場合エラーがでてできない）
 - [x]  #999 予約の一覧のTSVダウンロードの上限件数は500件ですか?
 - [x]  #987 フッタの内容の変更方法を教えてほしい（マニュアルに書きたい）
 - [x]  #928 利用者の新規登録で登録した「図書館」は何のメリットがありますか?
 - [x]  #1031 取り置き済みの予約の編集で、所蔵情報IDを編集できるかどうか? 
 - [x] #1037 「貸出期限切れの資料の一覧」画面で「予約」のフィルタのリンク先がおかしい
 - [x] #1038 ユーザインポートで利用者番号に不正な文字を含む場合にアカウント情報だけが作られてしまう （1.1系）
 - [x] #1057 #1067 
 - [x] #1069 資料のエクスポートで編者(contributor)が出力されない

* できればやりたい
- [ ] 請求記号ラベルの表示について
- [x] ログインなしで書誌詳細で予約リンクをたどって予約する説明
- [ ] 所蔵情報の新規入力画面の説明に、ひとつひとつの項目について詳細な説明を書く
- [ ] 書誌詳細の右メニューの説明をひとつひとつ書く
- [ ] 書誌詳細のひとつひとつの項目について詳細な説明を書く

**Comment by yegusa** [comment]
運用マニュアル 第10章 蔵書点検機能を利用する については、実装されてない機能だが、
消さずに残すことにする。

**Comment by yegusa** [comment]
まあ、マニュアル整備は、ぼちぼちやるので、マニュアル整備が全部できなかったとしても1.1.2のリリースはしてよいかと思います。

**Comment by yegusa** [comment]
マニュアル1.1.2はだいたいひととおり終了。あとは、できればやるってかんじのつもりです。

**Comment by yegusa** [comment]
1.1.2がリリースされたので未のものもありますが、クローズします。
